<a href="https://colab.research.google.com/github/karthik12794/23NE1A05B2_Final_Year_project_2027/blob/main/HomeAssist_01_Dataset_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q datasets

In [ ]:
from datasets import load_dataset

dataset = load_dataset("dipenbhuva/home-diy-repair-qa")

print(dataset)

README.md:   0%|          | 0.00/6.14k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

train.jsonl:   0%|          | 0.00/8.98M [00:00<?, ?B/s]

eval.jsonl:   0%|          | 0.00/2.25M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4000 [00:00<?, ? examples/s]

Generating eval split:   0%|          | 0/1000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'category', 'question', 'answer', 'equipment_problem', 'tools_required', 'steps', 'safety_info', 'tips'],
        num_rows: 4000
    })
    eval: Dataset({
        features: ['id', 'category', 'question', 'answer', 'equipment_problem', 'tools_required', 'steps', 'safety_info', 'tips'],
        num_rows: 1000
    })
})

In [ ]:
train = dataset["train"]
eval_data = dataset["eval"]

print("Training examples:", len(train))
print("Evaluation examples:", len(eval_data))

Training examples: 4000
Evaluation examples: 1000

In [ ]:
print(train[0])

{'id': 'qa_01384', 'category': 'electrical_repair', 'question': 'My ceiling light fixture is flickering intermittently. How do I fix this?', 'answer': 'Before you start, here are some useful things to know: A loose bulb or loose wire nut connection causes the vast majority of flickering light fixtures.\n\nNow, gather replacement bulb, voltage tester, stable ladder, wire nuts, and screwdriver set and follow these steps:\n\n1. Turn off the light and check that the bulb is screwed in firmly — a loose bulb is the most common cause of flickering\n2. Replace the bulb with a known working one to rule out a faulty bulb\n3. If flickering continues, turn off the breaker and verify power is off with a voltage tester\n4. Set up a stable ladder and remove the fixture mounting screws to lower the fixture canopy\n5. Check the wire nut connections — disconnect each one, re-twist the bare wire ends together tightly, and apply a new wire nut\n6. Remount the fixture, restore power, and monitor for continued flickering\n\nSafety note: Turn off the circuit breaker before accessing fixture wiring. Use a stable ladder on a flat surface — never stand on the top step.', 'equipment_problem': 'Ceiling light fixture flickering intermittently', 'tools_required': ['replacement bulb', 'voltage tester', 'stable ladder', 'wire nuts', 'screwdriver set'], 'steps': ['Turn off the light and check that the bulb is screwed in firmly — a loose bulb is the most common cause of flickering', 'Replace the bulb with a known working one to rule out a faulty bulb', 'If flickering continues, turn off the breaker and verify power is off with a voltage tester', 'Set up a stable ladder and remove the fixture mounting screws to lower the fixture canopy', 'Check the wire nut connections — disconnect each one, re-twist the bare wire ends together tightly, and apply a new wire nut', 'Remount the fixture, restore power, and monitor for continued flickering'], 'safety_info': 'Turn off the circuit breaker before accessing fixture wiring. Use a stable ladder on a flat surface — never stand on the top step.', 'tips': ['A loose bulb or loose wire nut connection causes the vast majority of flickering light fixtures']}

In [ ]:
from collections import Counter

categories = [row["category"] for row in train]

print(Counter(categories))

Counter({'hvac_maintenance': 814, 'plumbing_repair': 804, 'general_home_repair': 803, 'electrical_repair': 794, 'appliance_repair': 785})

In [ ]:
for category, count in Counter(categories).items():
    print(category, ":", count)

electrical_repair : 794
appliance_repair : 785
general_home_repair : 803
plumbing_repair : 804
hvac_maintenance : 814

In [ ]:
for category in set(categories):
    print("\n====================")
    print(category)
    print("====================")

    for row in train:
        if row["category"] == category:
            print("Question:", row["question"])
            print("Answer:", row["answer"])
            break

====================
hvac_maintenance
====================
Question: There is condensation forming on my air vent grilles. Is this a DIY repair or do I need a professional?
Answer: Yes, this is something you can fix yourself. Here is what to do.

Tools needed: hygrometer, dehumidifier, duct insulation wrap, and foil tape

1. Identify the cause — condensation on vents means indoor humidity is too high relative to the cold air coming from the vent
2. Check the humidity level in your home with a hygrometer — ideal is 30-50%
3. If humidity is high, run a dehumidifier in the affected area or the whole house
4. Check that the bathroom and kitchen exhaust fans are functioning and vented to the outside
5. Next, inspect the ductwork in the attic for poor insulation — uninsulated ducts sweat in humid conditions
6. Consider adding insulation wrap to exposed ductwork in unconditioned spaces like the attic

Be safe: Persistent condensation on vents can lead to mold growth on the ceiling or wall around the vent. Address high humidity promptly to prevent mold.

Helpful tips: Always vent bathroom exhaust fans to the outside, not into the attic — this is a major source of attic moisture problems.

====================
electrical_repair
====================
Question: My ceiling light fixture is flickering intermittently. How do I fix this?
Answer: Before you start, here are some useful things to know: A loose bulb or loose wire nut connection causes the vast majority of flickering light fixtures.

Now, gather replacement bulb, voltage tester, stable ladder, wire nuts, and screwdriver set and follow these steps:

1. Turn off the light and check that the bulb is screwed in firmly — a loose bulb is the most common cause of flickering
2. Replace the bulb with a known working one to rule out a faulty bulb
3. If flickering continues, turn off the breaker and verify power is off with a voltage tester
4. Set up a stable ladder and remove the fixture mounting screws to lower the fixture canopy
5. Check the wire nut connections — disconnect each one, re-twist the bare wire ends together tightly, and apply a new wire nut
6. Remount the fixture, restore power, and monitor for continued flickering

Safety note: Turn off the circuit breaker before accessing fixture wiring. Use a stable ladder on a flat surface — never stand on the top step.

====================
appliance_repair
====================
Question: What causes an oven light burned out and needs replacement and how do I fix it?
Answer: You can handle this repair at home. Grab replacement 40W appliance bulb, dry cloth, and oven mitt and follow these steps:

1. Turn off the oven and let it cool completely
2. Locate the light bulb cover inside the oven — it is usually a glass dome on the rear or side wall
3. Turn the glass cover counterclockwise to remove it — use a dry cloth for grip if it is stuck
4. After that, unscrew the old bulb and replace it with a new 40-watt appliance-rated bulb
5. Screw the glass cover back on by turning clockwise until snug
6. Turn on the oven to verify the new light works when the door is opened

A few things to keep in mind: Make sure the oven is completely cool before replacing the bulb. Use only appliance-rated bulbs — standard bulbs can shatter at oven temperatures. If the light still does not work with a new bulb, the socket or switch may need replacement.

====================
plumbing_repair
====================
Question: My kitchen sink is draining very slowly. Is this a DIY repair or do I need a professional?
Answer: This is usually a straightforward fix. You will need baking soda, white vinegar, kettle, and drain snake.

Follow these steps to resolve it:
1. Remove the sink stopper or strainer from the drain opening
2. Now, pour half a cup of baking soda followed by half a cup of white vinegar down the drain
3. Let the mixture fizz and work for 15 minutes to break down grease and buildup
4. Flush with a full kettle of boiling water poured slowly down the drain
5. If the drain is still slow, insert a drain snake into the drain opening

Important: Use caution when pouring boiling water — pour slowly to avoid splashing. Do not use boiling water if you have PVC drain pipes, as extreme heat can soften them.

One more thing — Baking soda and vinegar is the safest first-line treatment for slow drains before resorting to chemical cleaners.

====================
general_home_repair
====================
Question: The caulk around my bathtub is moldy and peeling. Can I fix this without calling a professional?
Answer: Tools: utility knife, caulk gun, 100% silicone caulk, rubbing alcohol, painter's tape, and clean cloth

1. Cut along both edges of the old caulk with a utility knife and peel it away in strips
2. Clean the joint thoroughly with rubbing alcohol or a mildew remover to kill mold and remove residue
3. Let the area dry completely — wait at least 2 hours for full drying
4. Next, apply painter's tape along both sides of the joint for clean, straight lines
5. Apply a continuous bead of 100% silicone caulk along the joint using a caulk gun
6. Smooth the bead with a wet finger or caulk smoothing tool, remove the tape immediately, and allow 24 hours to cure

Safety warning: Ensure adequate ventilation when using rubbing alcohol or mildew cleaners in an enclosed bathroom. Open a window or run the exhaust fan.

Additional advice: Remove the painter's tape immediately after smoothing — if you wait until the caulk sets, the tape will tear the caulk edge.

In [ ]:
from collections import Counter

category_counts = Counter(categories)

for category, count in category_counts.items():
    percentage = (count / len(train)) * 100
    print(category, ":", count, "(", round(percentage, 2), "%)")

electrical_repair : 794 ( 19.85 %)
appliance_repair : 785 ( 19.62 %)
general_home_repair : 803 ( 20.08 %)
plumbing_repair : 804 ( 20.1 %)
hvac_maintenance : 814 ( 20.35 %)

In [ ]:
for column in train.column_names:
    missing = sum(1 for row in train if row[column] is None or row[column] == "")
    print(column, ":", missing)

id : 0
category : 0
question : 0
answer : 0
equipment_problem : 0
tools_required : 0
steps : 0
safety_info : 0
tips : 0

In [ ]:
questions = [row["question"] for row in train]

print("Total questions:", len(questions))
print("Unique questions:", len(set(questions)))
print("Duplicate questions:", len(questions) - len(set(questions)))

Total questions: 4000
Unique questions: 1102
Duplicate questions: 2898

In [ ]:
from collections import defaultdict

question_categories = defaultdict(set)

for row in train:
    question_categories[row["question"]].add(row["category"])

conflicts = 0

for question, categories in question_categories.items():
    if len(categories) > 1:
        conflicts += 1

print("Questions with different categories:", conflicts)

Questions with different categories: 0

In [ ]:
unique_data = {}

for row in train:
    question = row["question"]

    if question not in unique_data:
        unique_data[question] = row

clean_train = list(unique_data.values())

print("Original training examples:", len(train))
print("Clean training examples:", len(clean_train))

Original training examples: 4000
Clean training examples: 1102

In [ ]:
from collections import Counter

clean_categories = [row["category"] for row in clean_train]

for category, count in Counter(clean_categories).items():
    print(category, ":", count)

electrical_repair : 166
appliance_repair : 314
general_home_repair : 242
plumbing_repair : 192
hvac_maintenance : 188

In [ ]:
lengths = [len(row["question"].split()) for row in clean_train]

print("Shortest question:", min(lengths), "words")
print("Longest question:", max(lengths), "words")
print("Average question length:", sum(lengths) / len(lengths))

Shortest question: 9 words
Longest question: 27 words
Average question length: 16.468239564428313

In [ ]:
import random

for row in random.sample(clean_train, 10):
    print("Question:", row["question"])
    print("Category:", row["category"])
    print("-" * 60)

Question: A floor vent register is rattling when the HVAC system runs. Step-by-step guide to fix this?
Category: hvac_maintenance
------------------------------------------------------------
Question: There is condensation forming on my air vent grilles. What is the best approach to fix this?
Category: hvac_maintenance
------------------------------------------------------------
Question: My deck board is cracked and splintering. Is this a DIY repair or do I need a professional?
Category: general_home_repair
------------------------------------------------------------
Question: The P-trap under my bathroom sink is leaking at the joints. Step-by-step guide to fix this?
Category: plumbing_repair
------------------------------------------------------------
Question: My refrigerator ice maker has stopped producing ice. What are the steps to repair this?
Category: appliance_repair
------------------------------------------------------------
Question: One room in my house is much warmer or cooler than the rest. How do I fix this?
Category: hvac_maintenance
------------------------------------------------------------
Question: My refrigerator is not cooling properly. Step-by-step guide to fix this?
Category: appliance_repair
------------------------------------------------------------
Question: My dimmer switch is flickering with LED bulbs. How do I troubleshoot this at home?
Category: electrical_repair
------------------------------------------------------------
Question: My oven light has burned out and needs replacement — is this something I can handle myself?
Category: appliance_repair
------------------------------------------------------------
Question: My door latch is not catching in the strike plate. Can I fix this without calling a professional?
Category: general_home_repair
------------------------------------------------------------

In [ ]:
label_names = [
    "appliance_repair",
    "electrical_repair",
    "general_home_repair",
    "hvac_maintenance",
    "plumbing_repair"
]

label_to_id = {
    label: i
    for i, label in enumerate(label_names)
}

for row in clean_train[:5]:
    print(row["category"], "→", label_to_id[row["category"]])

electrical_repair → 1
appliance_repair → 0
general_home_repair → 2
appliance_repair → 0
plumbing_repair → 4

In [ ]:
texts = []
labels = []

for row in clean_train:
    texts.append(row["question"])
    labels.append(label_to_id[row["category"]])

print("Total texts:", len(texts))
print("Total labels:", len(labels))

print("\nExample:")
print("Text:", texts[0])
print("Label:", labels[0])

Total texts: 1102
Total labels: 1102

Example:
Text: My ceiling light fixture is flickering intermittently. How do I fix this?
Label: 1

In [ ]:
from sklearn.model_selection import train_test_split

train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    texts,
    labels,
    test_size=0.20,
    random_state=42,
    stratify=labels
)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts,
    temp_labels,
    test_size=0.50,
    random_state=42,
    stratify=temp_labels
)

print("Training:", len(train_texts))
print("Validation:", len(val_texts))
print("Test:", len(test_texts))

Training: 881
Validation: 110
Test: 111

In [ ]:
from collections import Counter

print("Training distribution:")
print(Counter(train_labels))

print("\nValidation distribution:")
print(Counter(val_labels))

print("\nTest distribution:")
print(Counter(test_labels))

Training distribution:
Counter({0: 251, 2: 193, 4: 154, 3: 150, 1: 133})

Validation distribution:
Counter({0: 31, 2: 24, 4: 19, 3: 19, 1: 17})

Test distribution:
Counter({0: 32, 2: 25, 4: 19, 3: 19, 1: 16})

In [ ]:
!pip install -q transformers datasets evaluate accelerate scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 894.3 kB/s eta 0:00:00

In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch version: 2.11.0+cpu
GPU available: False

In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch version: 2.11.0+cu128
GPU available: True
GPU: Tesla T4

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=5
)

print("Model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model loaded successfully!

In [ ]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)

print("Using device:", device)

Using device: cuda

In [ ]:
print("clean_train:", "clean_train" in globals())
print("texts:", "texts" in globals())
print("label_to_id:", "label_to_id" in globals())
print("model:", "model" in globals())
print("tokenizer:", "tokenizer" in globals())

clean_train: False
texts: False
label_to_id: False
model: True
tokenizer: True

In [ ]:
from datasets import load_dataset

dataset = load_dataset("dipenbhuva/home-diy-repair-qa")

train = dataset["train"]
eval_data = dataset["eval"]

print("Training examples:", len(train))
print("Evaluation examples:", len(eval_data))

README.md:   0%|          | 0.00/6.14k [00:00<?, ?B/s]

train.jsonl:   0%|          | 0.00/8.98M [00:00<?, ?B/s]

eval.jsonl:   0%|          | 0.00/2.25M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4000 [00:00<?, ? examples/s]

Generating eval split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Training examples: 4000
Evaluation examples: 1000

In [ ]:
from collections import Counter
from sklearn.model_selection import train_test_split

label_names = [
    "appliance_repair",
    "electrical_repair",
    "general_home_repair",
    "hvac_maintenance",
    "plumbing_repair"
]

label_to_id = {
    label: i
    for i, label in enumerate(label_names)
}

unique_data = {}

for row in train:
    question = row["question"]

    if question not in unique_data:
        unique_data[question] = row

clean_train = list(unique_data.values())

texts = []
labels = []

for row in clean_train:
    texts.append(row["question"])
    labels.append(label_to_id[row["category"]])

train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    texts,
    labels,
    test_size=0.20,
    random_state=42,
    stratify=labels
)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts,
    temp_labels,
    test_size=0.50,
    random_state=42,
    stratify=temp_labels
)

print("Unique questions:", len(clean_train))
print("Training:", len(train_texts))
print("Validation:", len(val_texts))
print("Test:", len(test_texts))

Unique questions: 1102
Training: 881
Validation: 110
Test: 111

In [ ]:
train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=64
)

val_encodings = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=64
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=64
)

print("Training examples:", len(train_encodings["input_ids"]))
print("Validation examples:", len(val_encodings["input_ids"]))
print("Test examples:", len(test_encodings["input_ids"]))

Training examples: 881
Validation examples: 110
Test examples: 111

In [ ]:
import torch

class HomeAssistDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, index):
        item = {
            key: torch.tensor(value[index])
            for key, value in self.encodings.items()
        }

        item["labels"] = torch.tensor(self.labels[index])

        return item


train_dataset = HomeAssistDataset(train_encodings, train_labels)
val_dataset = HomeAssistDataset(val_encodings, val_labels)
test_dataset = HomeAssistDataset(test_encodings, test_labels)

print("Training dataset:", len(train_dataset))
print("Validation dataset:", len(val_dataset))
print("Test dataset:", len(test_dataset))

Training dataset: 881
Validation dataset: 110
Test dataset: 111

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./homeassist_distilbert",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    report_to="none"
)

print("Training configuration created successfully!")

Training configuration created successfully!

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="macro",
        zero_division=0
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

print("Evaluation metrics ready!")

Evaluation metrics ready!

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

print("Trainer created successfully!")

Trainer created successfully!

In [ ]:
print("Device:", device)
print("Training samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))
print("Test samples:", len(test_dataset))
print("Number of labels:", model.config.num_labels)
print("Labels:", label_names)

Device: cuda
Training samples: 881
Validation samples: 110
Test samples: 111
Number of labels: 5
Labels: ['appliance_repair', 'electrical_repair', 'general_home_repair', 'hvac_maintenance', 'plumbing_repair']

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=224, training_loss=0.3976236752101353, metrics={'train_runtime': 45.7422, 'train_samples_per_second': 77.04, 'train_steps_per_second': 4.897, 'total_flos': 31001099581680.0, 'train_loss': 0.3976236752101353, 'epoch': 4.0})

In [ ]:
test_results = trainer.evaluate(test_dataset)

print(test_results)

{'eval_loss': 0.07871603220701218, 'eval_accuracy': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_f1': 1.0}

In [ ]:
train_question_set = set(train_texts)
test_question_set = set(test_texts)

overlap = train_question_set.intersection(test_question_set)

print("Training questions:", len(train_question_set))
print("Test questions:", len(test_question_set))
print("Exact duplicates between train and test:", len(overlap))

Training questions: 881
Test questions: 111
Exact duplicates between train and test: 0